%% Creates output image from the hex file generated by FPGA
clear all;
close all;
%% Show the original image
figure;
principal_image = imread('grayImage.jpg');
imshow(principal_image);
%% Open the hex file
hexFile = fopen('Image.hex', 'r');
%% Read the hex file to an image and close it
img = fscanf(hexFile, '%x', [1 inf]);
fclose(hexFile); 
%% Reshape the image to a 256 x 256 image and display
outImg = reshape(img,[256 256]);
outImg = imrotate(outImg, 90);
figure, imshow(outImg,[])
%% Extract the final output and save it
finalRender = (outImg(129:256, 1:127));
imwrite(mat2gray(finalRender), 'finalImage.jpg');
figure, imshow(finalRender,[]);